# Generated by Django 3.1.4 on 2020-12-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='porfile-pic.png', upload_to='', verbose_name='Profile Picture'),
        ),
    ]
