# Generated by Django 3.1.4 on 2020-12-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الأسم')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الألكترونى')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='الرساله')),
            ],
        ),
    ]
