# Generated by Django 3.1.4 on 2020-12-17 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0002_auto_20201216_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerstatus',
            name='engineer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مهندس'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(blank=True, null=True, verbose_name='الطلب')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافه')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='عميل')),
            ],
            options={
                'verbose_name': 'طلب عمل',
                'verbose_name_plural': 'طلبات عمل',
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='RequestWorkOfEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='الأسم')),
                ('request', models.TextField(blank=True, null=True, verbose_name='الطلب')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافه')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مهندس')),
            ],
            options={
                'verbose_name': 'طلب العمل  مع مهندس',
                'verbose_name_plural': 'طلبات العمل  مع مهندس ',
                'ordering': ['customer_email'],
            },
        ),
        migrations.CreateModel(
            name='RequestWorkOfCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='م/البريد الألكترونى')),
                ('request', models.TextField(blank=True, null=True, verbose_name='الطلب')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافه')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='عميل')),
            ],
            options={
                'verbose_name': 'طلب العمل  من عميل',
                'verbose_name_plural': 'طلبات العمل  إلى عميل  ',
                'ordering': ['engineer_email'],
            },
        ),
    ]
