# Generated by Django 3.1.4 on 2020-12-18 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0005_bestengineer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestengineer',
            options={'ordering': ['engineer'], 'verbose_name': ' افضل مهندسين - الشهر', 'verbose_name_plural': 'افضل مهندسين - الشهر'},
        ),
        migrations.AlterField(
            model_name='bestengineer',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المهندس'),
        ),
        migrations.AlterField(
            model_name='bestengineer',
            name='month',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'إبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبمتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], null=True, verbose_name='الشهر'),
        ),
    ]
