# Generated by Django 3.1.4 on 2020-12-18 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0006_auto_20201218_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestengineer',
            options={'ordering': ['month'], 'verbose_name': ' افضل مهندسين - الشهر', 'verbose_name_plural': 'افضل مهندسين - الشهر'},
        ),
        migrations.RemoveField(
            model_name='bestengineer',
            name='engineer',
        ),
        migrations.AddField(
            model_name='bestengineer',
            name='engineer',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='المهندس'),
        ),
    ]
