# Generated by Django 3.1.4 on 2020-12-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20201218_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestengineer',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
