# Generated by Django 3.1.5 on 2021-01-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlobService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='اللون المفضل')),
                ('about', models.TextField(blank=True, null=True, verbose_name='نبذه')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافه')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الأسم')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='الهاتف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='الصوره')),
            ],
        ),
    ]
