# Generated by Django 3.1.5 on 2021-01-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_etlobservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlobservice',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الألكترونى'),
        ),
    ]
