# Generated by Django 3.1.5 on 2021-01-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_etlobservice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlobservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.service', verbose_name='الخدمه'),
        ),
    ]
