# Generated by Django 3.1.5 on 2021-01-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_etlobservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlobservice',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='العمر'),
        ),
    ]
