# Generated by Django 3.1.5 on 2021-01-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_etlobservice_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlobservice',
            name='age',
        ),
        migrations.RemoveField(
            model_name='etlobservice',
            name='image',
        ),
        migrations.AddField(
            model_name='etlobservice',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المدينه'),
        ),
    ]
